version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cat
    container_name: cat-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cat
  db:
      image: mysql:8.0
      container_name: cat-db
      restart: unless-stopped
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: cat
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_USER: cat
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
        - cat
  nginx:
    image: nginx:alpine
    container_name: cat-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - cat

networks:
  cat:
    driver: bridge
